<?php

return [
    'enabled' => env('PLAYWRIGHT_ENABLED', true),
    'node_binary' => env('PLAYWRIGHT_NODE_BINARY', 'node'),
    'script_path' => env('PLAYWRIGHT_SCRIPT_PATH', 'automation/playwright/cli.mjs'),
    'browser' => env('PLAYWRIGHT_BROWSER', 'chromium'),
    'headless' => env('PLAYWRIGHT_HEADLESS', true),
    'timeout_ms' => env('PLAYWRIGHT_TIMEOUT_MS', 45000),
    'navigation_timeout_ms' => env('PLAYWRIGHT_NAVIGATION_TIMEOUT_MS', 45000),
    'initial_wait_ms' => env('PLAYWRIGHT_INITIAL_WAIT_MS', 1500),
    'scroll_limit' => env('PLAYWRIGHT_SCROLL_LIMIT', 5),
    'scroll_pause_ms' => env('PLAYWRIGHT_SCROLL_PAUSE_MS', 1200),
    'post_limit' => env('PLAYWRIGHT_POST_LIMIT', 10),
    'retries' => env('PLAYWRIGHT_RETRIES', 2),
    'take_screenshot' => env('PLAYWRIGHT_TAKE_SCREENSHOT', false),
    'screenshot_dir' => env('PLAYWRIGHT_SCREENSHOT_DIR', 'storage/app/private/playwright/screenshots'),
    'user_agent' => env('PLAYWRIGHT_USER_AGENT'),
    'storage_state_path' => env('PLAYWRIGHT_STORAGE_STATE_PATH'),
    'default_source' => env('PLAYWRIGHT_DEFAULT_SOURCE', 'generic-feed'),
    'related_posts_enabled' => env('PLAYWRIGHT_RELATED_POSTS_ENABLED', true),
    'related_posts_inline' => env('PLAYWRIGHT_RELATED_POSTS_INLINE', false),
    'related_posts_source' => env('PLAYWRIGHT_RELATED_POSTS_SOURCE', 'generic-feed'),
    'related_posts_template' => env('PLAYWRIGHT_RELATED_POSTS_TEMPLATE', 'https://x.com/search?q={query}&src=typed_query&f=live'),
    'related_posts_limit' => env('PLAYWRIGHT_RELATED_POSTS_LIMIT', 6),
    'related_posts_ttl_hours' => env('PLAYWRIGHT_RELATED_POSTS_TTL_HOURS', 6),
    'social_context_enabled' => env('PLAYWRIGHT_SOCIAL_CONTEXT_ENABLED', true),
    'social_context_post_limit' => env('PLAYWRIGHT_SOCIAL_CONTEXT_POST_LIMIT', 2),
    'social_context_max_sources' => env('PLAYWRIGHT_SOCIAL_CONTEXT_MAX_SOURCES', 4),
    'social_context_query_length' => env('PLAYWRIGHT_SOCIAL_CONTEXT_QUERY_LENGTH', 120),
    'social_context_min_terms' => env('PLAYWRIGHT_SOCIAL_CONTEXT_MIN_TERMS', 2),
    'social_context_sources' => [
        [
            'key' => 'x-social-search',
            'name' => 'X',
            'platform' => 'x',
            'category' => 'social_context',
            'source_key' => 'generic-feed',
            'url_template' => 'https://x.com/search?q={query}&src=typed_query&f=live',
            'ready_selectors' => ['article', '[data-testid="tweet"]'],
            'extra_selectors' => [
                'postContainers' => ['article', '[data-testid="tweet"]'],
            ],
        ],
        [
            'key' => 'tiktok-social-search',
            'name' => 'TikTok',
            'platform' => 'tiktok',
            'category' => 'social_context',
            'source_key' => 'generic-feed',
            'url_template' => 'https://www.tiktok.com/search?q={query}',
            'ready_selectors' => ['[data-e2e*="search"]', '[data-e2e*="video"]'],
            'extra_selectors' => [
                'postContainers' => ['[data-e2e*="search"]', '[data-e2e*="video"]'],
            ],
        ],
        [
            'key' => 'youtube-social-search',
            'name' => 'YouTube',
            'platform' => 'youtube',
            'category' => 'social_context',
            'source_key' => 'generic-feed',
            'url_template' => 'https://www.youtube.com/results?search_query={query}',
            'ready_selectors' => ['ytd-video-renderer', 'ytd-reel-item-renderer'],
            'extra_selectors' => [
                'postContainers' => ['ytd-video-renderer', 'ytd-reel-item-renderer', 'ytd-rich-item-renderer'],
            ],
        ],
        [
            'key' => 'reddit-social-search',
            'name' => 'Reddit',
            'platform' => 'reddit',
            'category' => 'social_context',
            'source_key' => 'generic-feed',
            'url_template' => 'https://www.reddit.com/search/?q={query}&sort=new',
            'ready_selectors' => ['[data-testid="post-container"]', 'article'],
            'extra_selectors' => [
                'postContainers' => ['[data-testid="post-container"]', 'article'],
            ],
        ],
        [
            'key' => 'facebook-social-search',
            'name' => 'Facebook',
            'platform' => 'facebook',
            'category' => 'social_context',
            'source_key' => 'generic-feed',
            'url_template' => 'https://www.facebook.com/search/posts/?q={query}',
            'ready_selectors' => ['[role="article"]', 'div[role="feed"]'],
            'extra_selectors' => [
                'postContainers' => ['[role="article"]'],
            ],
        ],
    ],
    'verification_collection_enabled' => env('PLAYWRIGHT_VERIFICATION_COLLECTION_ENABLED', true),
    'verification_post_limit' => env('PLAYWRIGHT_VERIFICATION_POST_LIMIT', 3),
    'verification_scroll_limit' => env('PLAYWRIGHT_VERIFICATION_SCROLL_LIMIT', 2),
    'verification_max_items' => env('PLAYWRIGHT_VERIFICATION_MAX_ITEMS', 8),
    'verification_query_length' => env('PLAYWRIGHT_VERIFICATION_QUERY_LENGTH', 140),
    'verification_sources' => [
        [
            'key' => 'gma-news',
            'name' => 'GMA News',
            'category' => 'news',
            'source_key' => 'article-search',
            'url_template' => 'https://www.gmanetwork.com/news/search/?q={query}',
            'ready_selectors' => ['.gsc-webResult.gsc-result'],
            'extra_selectors' => [
                'siteLabel' => 'GMA News',
                'articleContainers' => ['.gsc-webResult.gsc-result'],
                'excludeSelectors' => ['.gsc-adBlock', '.gsc-cursor-box'],
            ],
        ],
        [
            'key' => 'ap-fact-check',
            'name' => 'AP Fact Check',
            'category' => 'fact_check',
            'source_key' => 'article-search',
            'url_template' => 'https://apnews.com/search?q={query}',
            'ready_selectors' => ['.PageList-items-item', 'main article'],
            'extra_selectors' => [
                'siteLabel' => 'AP Fact Check',
                'articleContainers' => ['.PageList-items-item', 'main article'],
                'excludeSelectors' => [
                    '#onetrust-consent-sdk',
                    '.onetrust-pc-dark-filter',
                    '.Page-header',
                    '.Header',
                    '.Footer',
                ],
                'dismissButtons' => ['#onetrust-reject-all-handler', '#onetrust-accept-btn-handler'],
            ],
        ],
        [
            'key' => 'politifact',
            'name' => 'PolitiFact',
            'category' => 'fact_check',
            'source_key' => 'article-search',
            'url_template' => 'https://www.politifact.com/search/factcheck/?q={query}',
            'ready_selectors' => ['article', '.o-platform-grid'],
            'extra_selectors' => [
                'siteLabel' => 'PolitiFact',
                'articleContainers' => ['main article', '.o-platform-grid article'],
                'excludeSelectors' => ['header', 'footer', '.m-cookie-banner'],
            ],
        ],
        [
            'key' => 'factcheck-org',
            'name' => 'FactCheck.org',
            'category' => 'fact_check',
            'source_key' => 'article-search',
            'url_template' => 'https://www.factcheck.org/?s={query}',
            'ready_selectors' => ['main article', '.archive-post'],
            'extra_selectors' => [
                'siteLabel' => 'FactCheck.org',
                'articleContainers' => ['main article', '.archive-post'],
                'excludeSelectors' => ['header', 'footer', '.fc-ask-widget'],
            ],
        ],
        [
            'key' => 'vera-files',
            'name' => 'VERA Files',
            'category' => 'fact_check',
            'source_key' => 'article-search',
            'url_template' => 'https://verafiles.org/?s={query}',
            'ready_selectors' => ['main article', 'article.post'],
            'extra_selectors' => [
                'siteLabel' => 'VERA Files',
                'articleContainers' => ['main article', 'article.post'],
                'excludeSelectors' => ['header', 'footer'],
            ],
        ],
        [
            'key' => 'rappler',
            'name' => 'Rappler',
            'category' => 'fact_check',
            'source_key' => 'article-search',
            'url_template' => 'https://www.rappler.com/?s={query}',
            'ready_selectors' => ['main article', '.post-card'],
            'extra_selectors' => [
                'siteLabel' => 'Rappler',
                'articleContainers' => ['main article', '.post-card', '.archive-post'],
                'excludeSelectors' => ['header', 'footer'],
            ],
        ],
    ],
    'target_urls' => array_values(array_filter(array_map(
        static fn (string $value) => trim($value),
        explode(',', (string) env('PLAYWRIGHT_TARGET_URLS', ''))
    ))),
    'analyze_posts' => env('PLAYWRIGHT_ANALYZE_POSTS', false),
    'automation_token' => env('PLAYWRIGHT_AUTOMATION_TOKEN'),
    'log_channel' => env('PLAYWRIGHT_LOG_CHANNEL', 'playwright'),
];
