<?php

namespace App\Services\Detections;

use Illuminate\Support\Str;

class FactCheckRatingNormalizer
{
    public const AI_GENERATED_MISINFORMATION = 'AI-generated, misinformation';
    public const MANIPULATED_MEDIA = 'Manipulated media';
    public const MISCAPTIONED = 'Miscaptioned';
    public const MISSING_CONTEXT = 'Missing context';
    public const MISLEADING = 'Misleading';
    public const PARTLY_FALSE = 'Partly false';
    public const NO_OFFICIAL_CONFIRMATION = 'No official confirmation found';
    public const FALSE = 'False';
    public const CONFIRMED = 'Confirmed';
    public const REVIEWED = 'Reviewed';
    private const CANONICAL_RATINGS = [
        self::AI_GENERATED_MISINFORMATION,
        self::MANIPULATED_MEDIA,
        self::MISCAPTIONED,
        self::MISSING_CONTEXT,
        self::MISLEADING,
        self::PARTLY_FALSE,
        self::NO_OFFICIAL_CONFIRMATION,
        self::FALSE,
        self::CONFIRMED,
        self::REVIEWED,
    ];

    public static function normalize(?string $rating, string ...$context): string
    {
        $rating = trim((string) $rating);
        $text = Str::lower(collect([$rating, ...$context])->filter()->implode(' '));

        if ($text === '') {
            return self::REVIEWED;
        }

        if (self::containsAny($text, ['not ai-generated', 'not ai generated', 'not synthetic', 'not a deepfake'])) {
            return self::FALSE;
        }

        if (self::containsAny($text, ['ai-generated', 'ai generated', 'synthetic', 'deepfake', 'generated by ai', 'created by ai'])) {
            return self::AI_GENERATED_MISINFORMATION;
        }

        if (self::containsAny($text, [
            'manipulated',
            'altered',
            'doctored',
            'edited image',
            'edited video',
            'spliced',
            'tampered',
            'fabricated image',
            'fabricated video',
            'digitally edited',
        ])) {
            return self::MANIPULATED_MEDIA;
        }

        if (self::containsAny($text, [
            'miscaptioned',
            'mis-captioned',
            'wrong caption',
            'incorrect caption',
            'used out of context',
            'out of context',
            'old photo',
            'old video',
            'old image',
            'old clip',
            'unrelated photo',
            'unrelated video',
            'recycled photo',
            'recycled image',
            'reused photo',
            'reused image',
        ])) {
            return self::MISCAPTIONED;
        }

        if (self::containsAny($text, ['missing context', 'needs context', 'lacks context', 'context missing'])) {
            return self::MISSING_CONTEXT;
        }

        if (self::containsAny($text, ['partly false', 'partly true', 'partially false', 'partially true'])) {
            return self::PARTLY_FALSE;
        }

        if (self::containsAny($text, ['misleading', 'misleads', 'deceptive'])) {
            return self::MISLEADING;
        }

        if (self::containsAny($text, ['no official confirmation', 'unsupported', 'unverified', 'unproven', 'no evidence'])) {
            return self::NO_OFFICIAL_CONFIRMATION;
        }

        if (self::containsAny($text, [
            'false',
            'fake',
            'not true',
            'untrue',
            'no truth',
            'incorrect',
            'fabricated',
            'hoax',
            'pants on fire',
            'scam',
        ])) {
            return self::FALSE;
        }

        if (self::containsAny($text, ['confirmed', 'true', 'correct', 'accurate', 'authentic', 'legitimate'])) {
            return self::CONFIRMED;
        }

        return $rating !== '' ? Str::limit($rating, 80, '') : self::REVIEWED;
    }

    public static function shortLabel(?string $rating, string ...$context): string
    {
        $rawRating = Str::lower(trim((string) $rating));

        if (preg_match('/^(?:mostly\s+)?(?:false|fake|hoax)$/i', $rawRating) === 1) {
            return self::FALSE;
        }

        $normalized = self::normalize($rating, ...$context);
        $text = Str::lower(collect([(string) $rating, ...$context])->filter()->implode(' '));

        if (! in_array($normalized, self::CANONICAL_RATINGS, true) && self::looksLikeFalseClaimReview($text)) {
            $normalized = self::FALSE;
        }

        return match ($normalized) {
            self::AI_GENERATED_MISINFORMATION => 'AI-Generated',
            self::MANIPULATED_MEDIA => 'Manipulated',
            self::MISSING_CONTEXT => 'Missing Context',
            self::PARTLY_FALSE => 'Partly False',
            self::NO_OFFICIAL_CONFIRMATION => 'Unconfirmed',
            default => in_array($normalized, self::CANONICAL_RATINGS, true)
                ? $normalized
                : Str::limit(Str::headline(Str::lower($normalized)), 18, ''),
        };
    }

    public static function verdictFor(string $rating): ?string
    {
        $rating = Str::lower($rating);

        if (self::containsAny($rating, [
            'ai-generated, misinformation',
            'ai-generated',
            'manipulated media',
            'manipulated',
            'miscaptioned',
            'misleading',
            'partly false',
            'false',
        ])) {
            return 'fake';
        }

        if (self::containsAny($rating, [
            'missing context',
            'no official confirmation',
            'unconfirmed',
            'unsupported',
            'reviewed',
            'needs review',
        ])) {
            return 'review';
        }

        if (self::containsAny($rating, ['confirmed', 'true', 'correct', 'accurate', 'authentic', 'legitimate'])) {
            return 'real';
        }

        return null;
    }

    public static function toneFor(string $rating): string
    {
        return match (self::verdictFor($rating)) {
            'fake' => 'danger',
            'real' => 'safe',
            'review' => 'warning',
            default => 'neutral',
        };
    }

    private static function containsAny(string $text, array $needles): bool
    {
        return Str::contains($text, $needles);
    }

    private static function looksLikeFalseClaimReview(string $text): bool
    {
        if (self::containsAny($text, ['mali-ta', 'maling balita', 'disinfo', 'misinformation', 'fake news'])) {
            return true;
        }

        return preg_match('/\bfact[\s-]?check\b.*\b(?:false|fake|hoax|no|not)\b/i', $text) === 1;
    }
}
